///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DBC3_IDE.DBC3_IDE.Login
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoginSuccess recording.
    /// </summary>
    [TestModule("6526a20c-9ffa-4b5e-85c0-3feec9c97884", ModuleType.Recording, 1)]
    public partial class LoginSuccess : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DBC3_IDE.DBC3_IDERepository repository.
        /// </summary>
        public static global::DBC3_IDE.DBC3_IDERepository repo = global::DBC3_IDE.DBC3_IDERepository.Instance;

        static LoginSuccess instance = new LoginSuccess();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginSuccess()
        {
            URL = "";
            Proxy = "";
            ChainID = "";
            Path = "";
            Password = "";
            Expect = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginSuccess Instance
        {
            get { return instance; }
        }

#region Variables

        string _URL;

        /// <summary>
        /// Gets or sets the value of variable URL.
        /// </summary>
        [TestVariable("0105e570-eb72-4956-9cd3-a04d8f6e07dd")]
        public string URL
        {
            get { return _URL; }
            set { _URL = value; }
        }

        string _Proxy;

        /// <summary>
        /// Gets or sets the value of variable Proxy.
        /// </summary>
        [TestVariable("37a4a9c3-1d95-4564-9233-68cc94100d29")]
        public string Proxy
        {
            get { return _Proxy; }
            set { _Proxy = value; }
        }

        string _ChainID;

        /// <summary>
        /// Gets or sets the value of variable ChainID.
        /// </summary>
        [TestVariable("2c30f528-dd64-45ef-8aaf-0b961aeb9518")]
        public string ChainID
        {
            get { return _ChainID; }
            set { _ChainID = value; }
        }

        string _Path;

        /// <summary>
        /// Gets or sets the value of variable Path.
        /// </summary>
        [TestVariable("3021c7b1-b663-41f8-9aba-d9e6fa4fef56")]
        public string Path
        {
            get { return _Path; }
            set { _Path = value; }
        }

        string _Password;

        /// <summary>
        /// Gets or sets the value of variable Password.
        /// </summary>
        [TestVariable("20e9462e-93ae-41ae-b3b2-06e1d598b0e5")]
        public string Password
        {
            get { return _Password; }
            set { _Password = value; }
        }

        string _Expect;

        /// <summary>
        /// Gets or sets the value of variable Expect.
        /// </summary>
        [TestVariable("bb5fb901-3842-4fdc-b0ae-50fce76b2e8c")]
        public string Expect
        {
            get { return _Expect; }
            set { _Expect = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DBC3_IDE_DOMAIN.Login.IconUser' at Center.", repo.DBC3_IDE_DOMAIN.Login.IconUserInfo, new RecordItemIndex(0));
            repo.DBC3_IDE_DOMAIN.Login.IconUser.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            MyTest1.Utils.logoutAndClickLogin(repo.DBC3_IDE_DOMAIN.Login.IconUserInfo, repo.DBC3_IDE_DOMAIN.Login.LoginItemInfo, repo.DBC3_IDE_DOMAIN.TabBar.ItemLogoutInfo, ValueConverter.ArgumentFromString<int>("duration", "0"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$URL' on item 'DBC3_IDE_DOMAIN.Login.TextboxURL'.", repo.DBC3_IDE_DOMAIN.Login.TextboxURLInfo, new RecordItemIndex(4));
            repo.DBC3_IDE_DOMAIN.Login.TextboxURL.Element.SetAttributeValue("Value", URL);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(5));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$Proxy' on item 'DBC3_IDE_DOMAIN.Login.TextboxProxy'.", repo.DBC3_IDE_DOMAIN.Login.TextboxProxyInfo, new RecordItemIndex(6));
            repo.DBC3_IDE_DOMAIN.Login.TextboxProxy.Element.SetAttributeValue("Value", Proxy);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(7));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$ChainID' on item 'DBC3_IDE_DOMAIN.Login.TextboxChainID'.", repo.DBC3_IDE_DOMAIN.Login.TextboxChainIDInfo, new RecordItemIndex(8));
            repo.DBC3_IDE_DOMAIN.Login.TextboxChainID.Element.SetAttributeValue("Value", ChainID);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(9));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DBC3_IDE_DOMAIN.Login.ButtonWallet' at Center.", repo.DBC3_IDE_DOMAIN.Login.ButtonWalletInfo, new RecordItemIndex(10));
            repo.DBC3_IDE_DOMAIN.Login.ButtonWallet.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(11));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$Path' on item 'DialogWindow.Text'.", repo.DialogWindow.TextInfo, new RecordItemIndex(12));
            repo.DialogWindow.Text.Element.SetAttributeValue("Text", Path);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(13));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DialogWindow.ButtonOpen' at Center.", repo.DialogWindow.ButtonOpenInfo, new RecordItemIndex(14));
            repo.DialogWindow.ButtonOpen.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(15));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$Password' on item 'DBC3_IDE_DOMAIN.Login.TextboxPassword'.", repo.DBC3_IDE_DOMAIN.Login.TextboxPasswordInfo, new RecordItemIndex(16));
            repo.DBC3_IDE_DOMAIN.Login.TextboxPassword.Element.SetAttributeValue("Value", Password);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(17));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DBC3_IDE_DOMAIN.Login.LoginButon' at Center.", repo.DBC3_IDE_DOMAIN.Login.LoginButonInfo, new RecordItemIndex(18));
            repo.DBC3_IDE_DOMAIN.Login.LoginButon.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(19));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$Expect) on item 'DBC3_IDE_DOMAIN.Login.Loginsuccess'.", repo.DBC3_IDE_DOMAIN.Login.LoginsuccessInfo, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.DBC3_IDE_DOMAIN.Login.LoginsuccessInfo, "InnerText", Expect);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(21));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
