///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DBC3_IDE.DBC3_IDE.TabBar
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateDeployFailed recording.
    /// </summary>
    [TestModule("028f0e3e-6296-4b5d-a494-03500f37a727", ModuleType.Recording, 1)]
    public partial class ValidateDeployFailed : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DBC3_IDE.DBC3_IDERepository repository.
        /// </summary>
        public static global::DBC3_IDE.DBC3_IDERepository repo = global::DBC3_IDE.DBC3_IDERepository.Instance;

        static ValidateDeployFailed instance = new ValidateDeployFailed();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateDeployFailed()
        {
            MessageDeploy = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateDeployFailed Instance
        {
            get { return instance; }
        }

#region Variables

        string _MessageDeploy;

        /// <summary>
        /// Gets or sets the value of variable MessageDeploy.
        /// </summary>
        [TestVariable("166be67a-cfbd-4761-a902-e0f2f3beb54f")]
        public string MessageDeploy
        {
            get { return _MessageDeploy; }
            set { _MessageDeploy = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>$MessageDeploy) on item 'DBC3_IDE_DOMAIN.TabBar.MessageDeployFailed'.", repo.DBC3_IDE_DOMAIN.TabBar.MessageDeployFailedInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.DBC3_IDE_DOMAIN.TabBar.MessageDeployFailedInfo, "InnerText", MessageDeploy);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
