///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DBC3_IDE.DBC3_IDE.DomainCode
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateDomainDefault recording.
    /// </summary>
    [TestModule("2582da86-6ef1-4b22-bcdf-3815f610cf65", ModuleType.Recording, 1)]
    public partial class ValidateDomainDefault : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DBC3_IDE.DBC3_IDERepository repository.
        /// </summary>
        public static global::DBC3_IDE.DBC3_IDERepository repo = global::DBC3_IDE.DBC3_IDERepository.Instance;

        static ValidateDomainDefault instance = new ValidateDomainDefault();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateDomainDefault()
        {
            TagValueDefault = "d21024301";
            Checked = "True";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateDomainDefault Instance
        {
            get { return instance; }
        }

#region Variables

        string _TagValueDefault;

        /// <summary>
        /// Gets or sets the value of variable TagValueDefault.
        /// </summary>
        [TestVariable("23814a4d-1f53-4aef-a60a-9eeee1240da9")]
        public string TagValueDefault
        {
            get { return _TagValueDefault; }
            set { _TagValueDefault = value; }
        }

        string _Checked;

        /// <summary>
        /// Gets or sets the value of variable Checked.
        /// </summary>
        [TestVariable("5702d339-1ff9-449b-b363-b6df9c544cc4")]
        public string Checked
        {
            get { return _Checked; }
            set { _Checked = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='(null)') on item 'DBC3_IDE_DOMAIN.Info.Name'.", repo.DBC3_IDE_DOMAIN.Info.NameInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.DBC3_IDE_DOMAIN.Info.NameInfo, "Value", (string)null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$TagValueDefault) on item 'DBC3_IDE_DOMAIN.Info.EditDbcDomain.SelectboxDomain'.", repo.DBC3_IDE_DOMAIN.Info.EditDbcDomain.SelectboxDomainInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.DBC3_IDE_DOMAIN.Info.EditDbcDomain.SelectboxDomainInfo, "TagValue", TagValueDefault);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked=$Checked) on item 'DBC3_IDE_DOMAIN.Info.EditDbcDomain.Checkbox_VisibleToAll'.", repo.DBC3_IDE_DOMAIN.Info.EditDbcDomain.Checkbox_VisibleToAllInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.DBC3_IDE_DOMAIN.Info.EditDbcDomain.Checkbox_VisibleToAllInfo, "Checked", Checked);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(5));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'DBC3_IDE_DOMAIN.Info.EditDbcDomain.TextLineOneInFunction'.", repo.DBC3_IDE_DOMAIN.Info.EditDbcDomain.TextLineOneInFunctionInfo, new RecordItemIndex(6));
            Validate.NotExists(repo.DBC3_IDE_DOMAIN.Info.EditDbcDomain.TextLineOneInFunctionInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(7));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
