///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DBC3_IDE.DBC3_IDE.EditDbcUser.Validation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckPropertyDefault recording.
    /// </summary>
    [TestModule("e30f0664-5121-4372-8506-291fdea62ae8", ModuleType.Recording, 1)]
    public partial class CheckPropertyDefault : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DBC3_IDE.DBC3_IDERepository repository.
        /// </summary>
        public static global::DBC3_IDE.DBC3_IDERepository repo = global::DBC3_IDE.DBC3_IDERepository.Instance;

        static CheckPropertyDefault instance = new CheckPropertyDefault();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckPropertyDefault()
        {
            NewVariable = "12121";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckPropertyDefault Instance
        {
            get { return instance; }
        }

#region Variables

        string _NewVariable;

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("9bb48077-2ebf-4087-97c6-fcbeae279556")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='(null)') on item 'DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.UserName'.", repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.UserNameInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.UserNameInfo, "TagValue", (string)null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='(null)') on item 'DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.UserID'.", repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.UserIDInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.UserIDInfo, "TagValue", (string)null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.CheckboxDisclosedToAll'.", repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.CheckboxDisclosedToAllInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.CheckboxDisclosedToAllInfo, "Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.CheckboxVisible'.", repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.CheckboxVisibleInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.CheckboxVisibleInfo, "Checked", "False");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
