///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DBC3_IDE.DBC3_IDE.SignEdit
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FillSignEdit recording.
    /// </summary>
    [TestModule("3c9287bb-fd97-480b-8b9d-d5930ec50ae2", ModuleType.Recording, 1)]
    public partial class FillSignEdit : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DBC3_IDE.DBC3_IDERepository repository.
        /// </summary>
        public static global::DBC3_IDE.DBC3_IDERepository repo = global::DBC3_IDE.DBC3_IDERepository.Instance;

        static FillSignEdit instance = new FillSignEdit();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FillSignEdit()
        {
            Name = "";
            Wallet = "";
            ContractID = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FillSignEdit Instance
        {
            get { return instance; }
        }

#region Variables

        string _Name;

        /// <summary>
        /// Gets or sets the value of variable Name.
        /// </summary>
        [TestVariable("ad160c1e-9e36-4cb5-bc26-7aaab9a6327a")]
        public string Name
        {
            get { return _Name; }
            set { _Name = value; }
        }

        string _Wallet;

        /// <summary>
        /// Gets or sets the value of variable Wallet.
        /// </summary>
        [TestVariable("228699bd-6988-4f0d-90fc-7cc0ac7a67c7")]
        public string Wallet
        {
            get { return _Wallet; }
            set { _Wallet = value; }
        }

        string _ContractID;

        /// <summary>
        /// Gets or sets the value of variable ContractID.
        /// </summary>
        [TestVariable("94e6197c-8f0a-4475-9e07-e0c26cd71cb7")]
        public string ContractID
        {
            get { return _ContractID; }
            set { _ContractID = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$Name' on item 'DBC3_IDE_DOMAIN.EditDbcSignEdit.Name'.", repo.DBC3_IDE_DOMAIN.EditDbcSignEdit.NameInfo, new RecordItemIndex(0));
            repo.DBC3_IDE_DOMAIN.EditDbcSignEdit.Name.Element.SetAttributeValue("Value", Name);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$Wallet' on item 'DBC3_IDE_DOMAIN.EditDbcSignEdit.SelectWallet'.", repo.DBC3_IDE_DOMAIN.EditDbcSignEdit.SelectWalletInfo, new RecordItemIndex(2));
            repo.DBC3_IDE_DOMAIN.EditDbcSignEdit.SelectWallet.Element.SetAttributeValue("TagValue", Wallet);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$ContractID' on item 'DBC3_IDE_DOMAIN.EditDbcSignEdit.ContractID'.", repo.DBC3_IDE_DOMAIN.EditDbcSignEdit.ContractIDInfo, new RecordItemIndex(4));
            repo.DBC3_IDE_DOMAIN.EditDbcSignEdit.ContractID.Element.SetAttributeValue("Value", ContractID);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(5));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
