///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DBC3_IDE.DBC3_IDE.GroupEdit
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FillDataGroupEdit recording.
    /// </summary>
    [TestModule("733fb7f5-17e8-40b3-a636-733363e493c6", ModuleType.Recording, 1)]
    public partial class FillDataGroupEdit : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DBC3_IDE.DBC3_IDERepository repository.
        /// </summary>
        public static global::DBC3_IDE.DBC3_IDERepository repo = global::DBC3_IDE.DBC3_IDERepository.Instance;

        static FillDataGroupEdit instance = new FillDataGroupEdit();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FillDataGroupEdit()
        {
            GroupName = "";
            TagValueDomain = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FillDataGroupEdit Instance
        {
            get { return instance; }
        }

#region Variables

        string _GroupName;

        /// <summary>
        /// Gets or sets the value of variable GroupName.
        /// </summary>
        [TestVariable("78af3c7c-a0ed-4193-9de4-6eee45ece179")]
        public string GroupName
        {
            get { return _GroupName; }
            set { _GroupName = value; }
        }

        string _TagValueDomain;

        /// <summary>
        /// Gets or sets the value of variable TagValueDomain.
        /// </summary>
        [TestVariable("0b7c52bc-a98e-4230-b7ba-86ed660fdfa7")]
        public string TagValueDomain
        {
            get { return _TagValueDomain; }
            set { _TagValueDomain = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$GroupName' on item 'DBC3_IDE_DOMAIN.GroupEdit.GroupName'.", repo.DBC3_IDE_DOMAIN.GroupEdit.GroupNameInfo, new RecordItemIndex(0));
            repo.DBC3_IDE_DOMAIN.GroupEdit.GroupName.Element.SetAttributeValue("Value", GroupName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$TagValueDomain' on item 'DBC3_IDE_DOMAIN.GroupEdit.SelectDomainGroup'.", repo.DBC3_IDE_DOMAIN.GroupEdit.SelectDomainGroupInfo, new RecordItemIndex(2));
            repo.DBC3_IDE_DOMAIN.GroupEdit.SelectDomainGroup.Element.SetAttributeValue("TagValue", TagValueDomain);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
