///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DBC3_IDE.DBC3_IDE.EditDbcUser
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddWalletAddress recording.
    /// </summary>
    [TestModule("a3216ab8-a22c-42b3-982c-9a41d80db167", ModuleType.Recording, 1)]
    public partial class AddWalletAddress : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DBC3_IDE.DBC3_IDERepository repository.
        /// </summary>
        public static global::DBC3_IDE.DBC3_IDERepository repo = global::DBC3_IDE.DBC3_IDERepository.Instance;

        static AddWalletAddress instance = new AddWalletAddress();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddWalletAddress()
        {
            WalletAdress = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddWalletAddress Instance
        {
            get { return instance; }
        }

#region Variables

        string _WalletAdress;

        /// <summary>
        /// Gets or sets the value of variable WalletAdress.
        /// </summary>
        [TestVariable("1a3bc822-7afb-4c3e-b8e1-c8819578e972")]
        public string WalletAdress
        {
            get { return _WalletAdress; }
            set { _WalletAdress = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.ButtonAdd' at Center.", repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.ButtonAddInfo, new RecordItemIndex(0));
            repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.ButtonAdd.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$WalletAdress' on item 'DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.TextboxWalletAddress1'.", repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.TextboxWalletAddress1Info, new RecordItemIndex(2));
            repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.TextboxWalletAddress1.Element.SetAttributeValue("TagValue", WalletAdress);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
