///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DBC3_IDE.DBC3_IDE.EditDbcUser
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ChooseWalletOption recording.
    /// </summary>
    [TestModule("2016e64e-da37-47c4-89e4-9035739f47d7", ModuleType.Recording, 1)]
    public partial class ChooseWalletOption : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DBC3_IDE.DBC3_IDERepository repository.
        /// </summary>
        public static global::DBC3_IDE.DBC3_IDERepository repo = global::DBC3_IDE.DBC3_IDERepository.Instance;

        static ChooseWalletOption instance = new ChooseWalletOption();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ChooseWalletOption()
        {
            TagValueWallet = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ChooseWalletOption Instance
        {
            get { return instance; }
        }

#region Variables

        string _TagValueWallet;

        /// <summary>
        /// Gets or sets the value of variable TagValueWallet.
        /// </summary>
        [TestVariable("0bf25a03-ad9d-4401-b529-6f0deb7dce47")]
        public string TagValueWallet
        {
            get { return _TagValueWallet; }
            set { _TagValueWallet = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$TagValueWallet' on item 'DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.SelectWallet'.", repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.SelectWalletInfo, new RecordItemIndex(0));
            repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.SelectWallet.Element.SetAttributeValue("TagValue", TagValueWallet);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
