///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DBC3_IDE.DBC3_IDE.EditDbcUser
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FillImformationDbcUser recording.
    /// </summary>
    [TestModule("4c3491e4-62e4-4a91-b8fd-53352a957f84", ModuleType.Recording, 1)]
    public partial class FillImformationDbcUser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DBC3_IDE.DBC3_IDERepository repository.
        /// </summary>
        public static global::DBC3_IDE.DBC3_IDERepository repo = global::DBC3_IDE.DBC3_IDERepository.Instance;

        static FillImformationDbcUser instance = new FillImformationDbcUser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FillImformationDbcUser()
        {
            UserName = "username";
            TagValueDomain = "1773ce30.d19ed2";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FillImformationDbcUser Instance
        {
            get { return instance; }
        }

#region Variables

        string _UserName;

        /// <summary>
        /// Gets or sets the value of variable UserName.
        /// </summary>
        [TestVariable("bba961f9-1d79-45c8-bf48-a290199af68b")]
        public string UserName
        {
            get { return _UserName; }
            set { _UserName = value; }
        }

        string _TagValueDomain;

        /// <summary>
        /// Gets or sets the value of variable TagValueDomain.
        /// </summary>
        [TestVariable("fce05ba2-1dd1-472b-91e3-f2ca5826d689")]
        public string TagValueDomain
        {
            get { return _TagValueDomain; }
            set { _TagValueDomain = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$UserName' on item 'DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.UserName'.", repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.UserNameInfo, new RecordItemIndex(0));
            repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.UserName.Element.SetAttributeValue("Value", UserName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$TagValueDomain' on item 'DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.SelectBoxDomain'.", repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.SelectBoxDomainInfo, new RecordItemIndex(2));
            repo.DBC3_IDE_DOMAIN.Edit_DBC_USER_NODE.SelectBoxDomain.Element.SetAttributeValue("TagValue", TagValueDomain);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
