///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DBC3_IDE.DNCWareNetwork
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GetNewWalletAddress recording.
    /// </summary>
    [TestModule("b064eb2c-02fa-40bd-b745-1d4a3ca6b384", ModuleType.Recording, 1)]
    public partial class GetNewWalletAddress : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DBC3_IDE.DBC3_IDERepository repository.
        /// </summary>
        public static global::DBC3_IDE.DBC3_IDERepository repo = global::DBC3_IDE.DBC3_IDERepository.Instance;

        static GetNewWalletAddress instance = new GetNewWalletAddress();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GetNewWalletAddress()
        {
            WallesAddress = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GetNewWalletAddress Instance
        {
            get { return instance; }
        }

#region Variables

        string _WallesAddress;

        /// <summary>
        /// Gets or sets the value of variable WallesAddress.
        /// </summary>
        [TestVariable("4b801b75-3874-4418-beee-ec7609e0e584")]
        public string WallesAddress
        {
            get { return _WallesAddress; }
            set { _WallesAddress = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            MyTest1.Utils.logoutAndLogin(repo.DNCWAREBlockChain3.HomePage.Logout.LogoutButtonInfo, repo.DNCWAREBlockChain3.HomePage.Logout.OKButtonInfo, repo.DNCWAREBlockChain3.Login.LinkCreateNewWalletInfo, ValueConverter.ArgumentFromString<int>("duration", "30"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'DNCWAREBlockChain3.HomePage.WalletAddress' and assigning its value to variable 'WallesAddress'.", repo.DNCWAREBlockChain3.HomePage.WalletAddressInfo, new RecordItemIndex(2));
            WallesAddress = repo.DNCWAREBlockChain3.HomePage.WalletAddress.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
