///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DBC3_IDE.DNCWareNetwork
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Search recording.
    /// </summary>
    [TestModule("52656ca7-d66e-4071-a4fd-2a8930c4d153", ModuleType.Recording, 1)]
    public partial class Search : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DBC3_IDE.DBC3_IDERepository repository.
        /// </summary>
        public static global::DBC3_IDE.DBC3_IDERepository repo = global::DBC3_IDE.DBC3_IDERepository.Instance;

        static Search instance = new Search();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Search()
        {
            SearchValue = "c1domain";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Search Instance
        {
            get { return instance; }
        }

#region Variables

        string _SearchValue;

        /// <summary>
        /// Gets or sets the value of variable SearchValue.
        /// </summary>
        [TestVariable("5f25a6e5-22dd-48e4-b1b1-cfd690fae9cf")]
        public string SearchValue
        {
            get { return _SearchValue; }
            set { _SearchValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$SearchValue' on item 'DNCWAREBlockChain3.HomePage.SearchText'.", repo.DNCWAREBlockChain3.HomePage.SearchTextInfo, new RecordItemIndex(0));
            repo.DNCWAREBlockChain3.HomePage.SearchText.Element.SetAttributeValue("Value", SearchValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DNCWAREBlockChain3.HomePage.SearchButton' at Center.", repo.DNCWAREBlockChain3.HomePage.SearchButtonInfo, new RecordItemIndex(2));
            repo.DNCWAREBlockChain3.HomePage.SearchButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
